### ISSUE TITLE
JOSS Paper: The Tables are Partially Visible

### ISSUE THREAD

**Issue by B3J4y** [wetransform-os/ProMCDA#18]
In my PDF, none of the tables are visible. @Flaminietta, could you please correct the source file so that the tables are viewable? Attached is a picture showing how the tables appear to me:

![half_visible_table](https://github.com/wetransform-os/ProMCDA/assets/1398738/63156be0-9a6c-46a9-aef8-0004c70fc11f)

Is this a problem specific to the PDF reader I'm using?

**Comment by Flaminietta** [comment]
Hi @B3J4y, paper.pdf file (in the branch main of my repository) displays all tables just fine. The problem is in the preprint article and honestly, I am not quite sure what I can do to solve it. I can try to use different file extensions for the pictures and ask editorialbot to regenerate the preprint.

**Comment by Flaminietta** [comment]
@editorialbot generate pdf

**Comment by Flaminietta** [comment]
@editorialbot generate preprint

**Comment by Flaminietta** [comment]
I've tried with PDF and JPG files but the problem in the preprint persists.

**Comment by Flaminietta** [comment]
Hello again @B3J4y, the problem seems to be solved now: https://github.com/openjournals/joss-papers/actions/runs/7460439873.

**Comment by B3J4y** [comment]
Thank you. How do I see the resulting PDF, now? 🙂

**Comment by Flaminietta** [comment]
> Thank you. How do I see the resulting PDF, now? 🙂

I can see it in the artifacts, either [in my workflow artifact](https://github.com/wetransform-os/ProMCDA/actions/runs/7460417330) or [in the preprint](https://github.com/openjournals/joss-papers/actions/runs/7460439873) created by the @editorialbot (but then you have to compile the tex file).

**Comment by B3J4y** [comment]
Thank you very much.
