### ISSUE TITLE
Better code quality with static code analysis

### ISSUE THREAD

**Issue by B3J4y** [wetransform-os/ProMCDA#20]
There are some flaws in your code that could be addressed through static code analysis. For a lighter version focused mostly on code style, you can use flake8. The command for this is ```flake8 ./mcda```. Many of these issues can be automatically fixed by your IDE. For a more rigorous code analysis, you can use pylint, which delves deeper into code quality. The command for this is ```pylint ./mcda/**/*.py```. Addressing these issues after a long development process can be a significant workload. However, once it's done, the ongoing effort is minimal, and the code quality receives a substantial boost.

From my perspective, using static code analysis is not mandatory for the review, but it's a valuable addition to enhance code quality.

**Comment by Flaminietta** [comment]
Hi, I have never used those tools and I am happy to try them out. I'll let you know about any progress in this thread. I'll open a new branch if I see the workload is relatively big.
