### ISSUE TITLE
Include sample data inside the package

### ISSUE THREAD

**Issue by paulrougieux** [wetransform-os/ProMCDA#25]
Sample data should be stored within the package so that users can run code examples. 

See https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distutils

Related to issue https://github.com/wetransform-os/ProMCDA/issues/19 and to the JOSS review https://github.com/openjournals/joss-reviews/issues/6190

**Comment by B3J4y** [comment]
Here is sample data already included: https://github.com/wetransform-os/ProMCDA/pull/21
