### ISSUE TITLE
Remove hard-coded paths

### ISSUE THREAD

**Issue by Flaminietta** [wetransform-os/ProMCDA#41]
We remove any hard-coded paths from within the code by following the suggestion of @paulrougieux: https://github.com/wetransform-os/ProMCDA/issues/19#issuecomment-1920558504.

All needed input files (e.g., the input matrix) will be stored in a default directory inside the root directory of ProMCDA. However, the user is allowed to change the position of this directory by setting a custom directory path in the environment:

`export CUSTOM_DIRECTORY_PATH=/path/to/custom/directory`

This allows the user to customize the directory path without modifying the source code of the Python package.

**Comment by paulrougieux** [comment]
- Great that the directory can be specified with an environment variable.
- Users might have many packages on their systems which require configuration through environment variables. the name of the environment variable should include the name of your package for example PROMCDA_DIR, PROMCDA_DIRECTORY_PATH, or similar.
